export interface DeepThought {
  text: string;
  author?: string;
  type: "quote" | "prompt";
}

export const DEEP_THOUGHTS: DeepThought[] = [
  { text: "The impediment to action advances action. What stands in the way becomes the way.", author: "Marcus Aurelius", type: "quote" },
  { text: "What would you attempt to do if you knew you could not fail?", type: "prompt" },
  { text: "We suffer more often in imagination than in reality.", author: "Seneca", type: "quote" },
  { text: "What is the one thing you're avoiding that would change everything?", type: "prompt" },
  { text: "A man who dares to waste one hour of time has not discovered the value of life.", author: "Charles Darwin", type: "quote" },
  { text: "If you lost everything tomorrow, what would you rebuild first?", type: "prompt" },
  { text: "The best time to plant a tree was 20 years ago. The second best time is now.", author: "Chinese Proverb", type: "quote" },
  { text: "What would the person you want to become do today?", type: "prompt" },
  { text: "No man is free who is not master of himself.", author: "Epictetus", type: "quote" },
  { text: "What are you holding onto that's holding you back?", type: "prompt" },
  { text: "The only way to do great work is to love what you do.", author: "Steve Jobs", type: "quote" },
  { text: "If today were your last day, would you be proud of how you spent it?", type: "prompt" },
  { text: "He who has a why to live can bear almost any how.", author: "Friedrich Nietzsche", type: "quote" },
  { text: "What fear is disguising itself as a logical reason not to act?", type: "prompt" },
  { text: "Waste no more time arguing about what a good man should be. Be one.", author: "Marcus Aurelius", type: "quote" },
  { text: "Who in your life deserves more of your attention than your phone does?", type: "prompt" },
  { text: "The mind is everything. What you think you become.", author: "Buddha", type: "quote" },
  { text: "What would you do differently if nobody was watching?", type: "prompt" },
  { text: "It is not that we have a short time to live, but that we waste a great deal of it.", author: "Seneca", type: "quote" },
  { text: "What is the most important problem you could be working on right now — and why aren't you?", type: "prompt" },
  { text: "The happiness of your life depends upon the quality of your thoughts.", author: "Marcus Aurelius", type: "quote" },
  { text: "What would you tell your 10-years-younger self?", type: "prompt" },
  { text: "Knowing is not enough, we must apply. Willing is not enough, we must do.", author: "Bruce Lee", type: "quote" },
  { text: "What are you pretending not to know?", type: "prompt" },
  { text: "The world as we have created it is a process of our thinking. It cannot be changed without changing our thinking.", author: "Albert Einstein", type: "quote" },
  { text: "If you could master one skill overnight, what would it be — and what does that tell you?", type: "prompt" },
  { text: "Begin at once to live, and count each separate day as a separate life.", author: "Seneca", type: "quote" },
  { text: "What is the conversation you've been avoiding?", type: "prompt" },
  { text: "The unexamined life is not worth living.", author: "Socrates", type: "quote" },
  { text: "What would you do if you had 10x more confidence?", type: "prompt" },
  { text: "I am not what happened to me, I am what I choose to become.", author: "Carl Jung", type: "quote" },
  { text: "What does your ideal ordinary Tuesday look like five years from now?", type: "prompt" },
  { text: "Desire is a contract you make with yourself to be unhappy until you get what you want.", author: "Naval Ravikant", type: "quote" },
  { text: "What would happen if you just... started?", type: "prompt" },
  { text: "The things you think about determine the quality of your mind.", author: "Marcus Aurelius", type: "quote" },
  { text: "Who do you admire — and what specifically about them do you want to embody?", type: "prompt" },
  { text: "An unexamined idea, to paraphrase Socrates, is not worth having.", author: "Richard Feynman", type: "quote" },
  { text: "What is the kindest thing you could do for yourself today?", type: "prompt" },
  { text: "We are what we repeatedly do. Excellence, then, is not an act, but a habit.", author: "Will Durant", type: "quote" },
  { text: "What would you stop doing if you truly valued your time?", type: "prompt" },
  { text: "The best revenge is not to be like your enemy.", author: "Marcus Aurelius", type: "quote" },
  { text: "What belief, if you let go of it, would change your life?", type: "prompt" },
  { text: "Simplicity is the ultimate sophistication.", author: "Leonardo da Vinci", type: "quote" },
  { text: "What is one thing you could do today that your future self would thank you for?", type: "prompt" },
  { text: "The only true wisdom is in knowing you know nothing.", author: "Socrates", type: "quote" },
  { text: "Are you building the life you want, or just reacting to the life you have?", type: "prompt" },
  { text: "If you are distressed by anything external, the pain is not due to the thing itself, but to your estimate of it.", author: "Marcus Aurelius", type: "quote" },
  { text: "What would you attempt if social judgment didn't exist?", type: "prompt" },
  { text: "The privilege of a lifetime is being who you are.", author: "Joseph Campbell", type: "quote" },
  { text: "What hard truth are you dancing around instead of confronting?", type: "prompt" },
  { text: "Luck is what happens when preparation meets opportunity.", author: "Seneca", type: "quote" },
  { text: "If you could only teach one lesson to the next generation, what would it be?", type: "prompt" },
  { text: "The obstacle is the way.", author: "Ryan Holiday", type: "quote" },
  { text: "What would change if you stopped comparing yourself to others?", type: "prompt" },
  { text: "A ship in harbor is safe, but that is not what ships are built for.", author: "John A. Shedd", type: "quote" },
  { text: "What does success actually mean to you — not what you were told it means?", type: "prompt" },
  { text: "You have power over your mind — not outside events. Realize this, and you will find strength.", author: "Marcus Aurelius", type: "quote" },
  { text: "What are you grateful for that you usually take for granted?", type: "prompt" },
  { text: "In the middle of difficulty lies opportunity.", author: "Albert Einstein", type: "quote" },
  { text: "What legacy do you want to leave behind?", type: "prompt" },
  { text: "Memento mori — remember that you will die.", author: "Stoic Meditation", type: "quote" },
  { text: "If you could have dinner with anyone, living or dead, what would you ask them?", type: "prompt" },
  { text: "The man who moves a mountain begins by carrying away small stones.", author: "Confucius", type: "quote" },
  { text: "What is the smallest step you can take toward your biggest goal?", type: "prompt" },
  { text: "Freedom is the only worthy goal in life. It is won by disregarding things that lie beyond our control.", author: "Epictetus", type: "quote" },
  { text: "What would a truly peaceful day look like for you?", type: "prompt" },
  { text: "Life is really simple, but we insist on making it complicated.", author: "Confucius", type: "quote" },
  { text: "What are you doing out of obligation that you could release?", type: "prompt" },
  { text: "The soul becomes dyed with the color of its thoughts.", author: "Marcus Aurelius", type: "quote" },
  { text: "If money were no object, how would you spend your time?", type: "prompt" },
  { text: "Everything we hear is an opinion, not a fact. Everything we see is a perspective, not the truth.", author: "Marcus Aurelius", type: "quote" },
  { text: "What habit, if started today, would transform your life in a year?", type: "prompt" },
  { text: "The mind that is anxious about the future is miserable.", author: "Seneca", type: "quote" },
  { text: "What is something you need to forgive yourself for?", type: "prompt" },
  { text: "Be tolerant with others and strict with yourself.", author: "Marcus Aurelius", type: "quote" },
  { text: "What would happen if you gave yourself permission to rest without guilt?", type: "prompt" },
  { text: "The secret of happiness is not in doing what one likes, but in liking what one does.", author: "James Barrie", type: "quote" },
  { text: "What is the most courageous thing you could do this week?", type: "prompt" },
  { text: "Man is not worried by real problems so much as by his imagined anxieties about real problems.", author: "Epictetus", type: "quote" },
  { text: "What relationship in your life needs the most attention right now?", type: "prompt" },
  { text: "The art of being wise is the art of knowing what to overlook.", author: "William James", type: "quote" },
  { text: "If you were coaching yourself, what advice would you give?", type: "prompt" },
  { text: "Dwell on the beauty of life. Watch the stars, and see yourself running with them.", author: "Marcus Aurelius", type: "quote" },
  { text: "What are you making harder than it needs to be?", type: "prompt" },
  { text: "To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.", author: "Ralph Waldo Emerson", type: "quote" },
  { text: "What would your life look like if you said no to everything that doesn't excite you?", type: "prompt" },
  { text: "The first and greatest victory is to conquer yourself.", author: "Plato", type: "quote" },
  { text: "What did you learn from your last failure that you haven't applied yet?", type: "prompt" },
  { text: "How long are you going to wait before you demand the best for yourself?", author: "Epictetus", type: "quote" },
  { text: "What would you create if you knew nobody would criticize it?", type: "prompt" },
  { text: "The happiness of those who want to be popular depends on others. The happiness of those who seek pleasure fluctuates. But the happiness of the wise grows out of their own free acts.", author: "Marcus Aurelius", type: "quote" },
  { text: "What are the three things that matter most to you? Are you giving them enough time?", type: "prompt" },
  { text: "When you arise in the morning, think of what a precious privilege it is to be alive — to breathe, to think, to enjoy, to love.", author: "Marcus Aurelius", type: "quote" },
  { text: "What would you do if you weren't afraid of looking foolish?", type: "prompt" },
  { text: "Judge each day not by the harvest you reap but by the seeds you plant.", author: "Robert Louis Stevenson", type: "quote" },
  { text: "What unnecessary complexity could you eliminate from your life this week?", type: "prompt" },
  { text: "The whole future lies in uncertainty: live immediately.", author: "Seneca", type: "quote" },
  { text: "When was the last time you did something for the first time?", type: "prompt" },
  { text: "Wealth consists not in having great possessions, but in having few wants.", author: "Epictetus", type: "quote" },
  { text: "What is the difference between who you are and who you want to be?", type: "prompt" },
  { text: "Very little is needed to make a happy life; it is all within yourself, in your way of thinking.", author: "Marcus Aurelius", type: "quote" },
  { text: "What question are you afraid to ask because you might not like the answer?", type: "prompt" },
  { text: "It does not matter how slowly you go as long as you do not stop.", author: "Confucius", type: "quote" },
  { text: "What part of your daily routine is serving someone else's priorities instead of yours?", type: "prompt" },
  { text: "The best fighter is never angry.", author: "Lao Tzu", type: "quote" },
  { text: "If you could guarantee one outcome for this year, what would it be?", type: "prompt" },
  { text: "Not how long, but how well you have lived is the main thing.", author: "Seneca", type: "quote" },
  { text: "What would the most disciplined version of you do right now?", type: "prompt" },
  { text: "The only person you are destined to become is the person you decide to be.", author: "Ralph Waldo Emerson", type: "quote" },
  { text: "What is one boundary you need to set or enforce?", type: "prompt" },
  { text: "No person is free who is not master of himself.", author: "Epictetus", type: "quote" },
  { text: "What would you do with an extra hour every day?", type: "prompt" },
  { text: "Amor fati — love your fate.", author: "Friedrich Nietzsche", type: "quote" },
  { text: "What are you tolerating that you shouldn't be?", type: "prompt" },
  { text: "The wise man does at once what the fool does finally.", author: "Baltasar Gracián", type: "quote" },
  { text: "What brings you energy — and what drains it?", type: "prompt" },
  { text: "Think of the life you want to live and then see if what you are doing is moving you in that direction.", author: "Ralph Waldo Emerson", type: "quote" },
  { text: "What is one thing you can simplify today?", type: "prompt" },
  { text: "All cruelty springs from weakness.", author: "Seneca", type: "quote" },
  { text: "If you could send a message to everyone on Earth, what would you say?", type: "prompt" },
  { text: "What you do makes a difference, and you have to decide what kind of difference you want to make.", author: "Jane Goodall", type: "quote" },
  { text: "What would it take for you to feel truly at peace?", type: "prompt" },
  { text: "The mind adapted to the present possesses all things.", author: "Marcus Aurelius", type: "quote" },
  { text: "What is the most important thing you learned this year?", type: "prompt" },
  { text: "Difficulties strengthen the mind, as labor does the body.", author: "Seneca", type: "quote" },
  { text: "What would your 80-year-old self tell you to stop worrying about?", type: "prompt" },
  { text: "Do every act of your life as though it were the very last act of your life.", author: "Marcus Aurelius", type: "quote" },
  { text: "What are you saying yes to that's actually a no?", type: "prompt" },
  { text: "He suffers more than necessary, who suffers before it is necessary.", author: "Seneca", type: "quote" },
  { text: "What is one thing you could teach someone that would genuinely help them?", type: "prompt" },
  { text: "The things you own end up owning you.", author: "Chuck Palahniuk", type: "quote" },
  { text: "What would make today meaningful, even if nothing else goes right?", type: "prompt" },
  { text: "Choose not to be harmed — and you won't feel harmed. Don't feel harmed — and you haven't been.", author: "Marcus Aurelius", type: "quote" },
  { text: "What would you pursue if you had unlimited patience?", type: "prompt" },
  { text: "The more you seek the uncomfortable, the more you will become comfortable.", author: "Conor McGregor", type: "quote" },
  { text: "What is the story you keep telling yourself that might not be true?", type: "prompt" },
  { text: "Associate with people who are likely to improve you.", author: "Seneca", type: "quote" },
  { text: "What have you been putting off that would take less than an hour to do?", type: "prompt" },
  { text: "The greatest weapon against stress is our ability to choose one thought over another.", author: "William James", type: "quote" },
  { text: "What does your intuition say that your logic keeps overruling?", type: "prompt" },
  { text: "Caretake this moment. Immerse yourself in its particulars.", author: "Epictetus", type: "quote" },
  { text: "What part of your identity are you most attached to — and what would happen if you let it go?", type: "prompt" },
  { text: "True happiness is to enjoy the present, without anxious dependence upon the future.", author: "Seneca", type: "quote" },
  { text: "What is the bravest thing you've ever done — and how can you channel that energy today?", type: "prompt" },
  { text: "Perfection of character is this: to live each day as if it were your last.", author: "Marcus Aurelius", type: "quote" },
  { text: "What would you want written on your tombstone?", type: "prompt" },
  { text: "The purpose of life is not to be happy. It is to be useful, to be honorable, to be compassionate.", author: "Ralph Waldo Emerson", type: "quote" },
  { text: "What is the one thing you need to hear right now that nobody is telling you?", type: "prompt" },
  { text: "Nothing is permanent in this wicked world — not even our troubles.", author: "Charlie Chaplin", type: "quote" },
  { text: "What would your life look like if you stopped waiting for permission?", type: "prompt" },
  { text: "If it is not right do not do it; if it is not true do not say it.", author: "Marcus Aurelius", type: "quote" },
  { text: "What are you chasing that, once caught, probably won't make you happier?", type: "prompt" },
  { text: "The best way to find yourself is to lose yourself in the service of others.", author: "Mahatma Gandhi", type: "quote" },
  { text: "What is the most generous interpretation of someone's actions that frustrated you recently?", type: "prompt" },
  { text: "He who is not a good servant will not be a good master.", author: "Plato", type: "quote" },
  { text: "What would you do today if you truly believed in yourself?", type: "prompt" },
  { text: "The mind is its own place, and in itself can make a heaven of hell, a hell of heaven.", author: "John Milton", type: "quote" },
  { text: "What are you overcomplicating that could be simple?", type: "prompt" },
  { text: "It is the power of the mind to be unconquerable.", author: "Seneca", type: "quote" },
  { text: "What matters most to you right now — not last year, not someday — right now?", type: "prompt" },
  { text: "Character is fate.", author: "Heraclitus", type: "quote" },
  { text: "What is one assumption you hold that you've never questioned?", type: "prompt" },
];

export function getTodayThought(): DeepThought {
  const now = new Date();
  const start = new Date(now.getFullYear(), 0, 0);
  const diff = now.getTime() - start.getTime();
  const dayOfYear = Math.floor(diff / (1000 * 60 * 60 * 24));
  return DEEP_THOUGHTS[dayOfYear % DEEP_THOUGHTS.length];
}
