import type { ProjectSpec } from "../types";

export const aiProjects: ProjectSpec[] = [
  {
    slug: "autograd-engine",
    pillar: "ai",
    title: "Autograd Engine (micrograd)",
    tagline: "Backpropagation from first principles in ~150 lines — then train a real net with it.",
    difficulty: "medium",
    estHours: 12,
    overview:
      "Build a scalar autograd engine à la Karpathy's micrograd: a Value class that records the computation graph and backpropagates gradients via the chain rule, then a tiny neural-network library (Neuron/Layer/MLP) on top, trained on a toy classification dataset. After this, PyTorch's .backward() is no longer magic — you will have written it. The highest insight-per-hour project in all of deep learning.",
    buildSteps: [
      "Value class with +, *, tanh/relu, and a _backward closure per operation",
      "Topological sort of the graph and a backward() that applies the chain rule in reverse",
      "Gradient-check against tiny numerical derivatives (the moment of truth)",
      "Neuron/Layer/MLP classes; train on make_moons with a manual SGD loop",
      "Plot the decision boundary evolving over epochs",
      "Watch Karpathy's video AFTER attempting each stage yourself — compare choices",
    ],
    stretchGoals: [
      "Tensor (numpy-backed) version with broadcasting-aware gradients",
      "Add Adam and momentum to your optimizer and compare convergence",
    ],
    skills: ["backpropagation", "computational graphs", "chain rule", "gradient checking"],
    topicSlugs: ["neural-nets-backprop", "calculus", "training-dynamics"],
  },
  {
    slug: "mnist-from-scratch",
    pillar: "ai",
    title: "MNIST in Pure NumPy",
    tagline: "A 2-layer network hitting 97%+ with nothing but matrices — no framework.",
    difficulty: "medium",
    estHours: 10,
    overview:
      "Train a digit classifier on MNIST using only NumPy: forward pass, softmax + cross-entropy, hand-derived backprop through both layers, mini-batch SGD. Where the autograd project teaches the graph abstraction, this one teaches the matrix reality — shapes, broadcasting, and vectorization under your full control. Hitting 97% with code you can read top-to-bottom in five minutes is a genuine milestone moment.",
    buildSteps: [
      "Load MNIST (raw IDX files), normalize, one-hot labels",
      "Forward pass: 784→128→10 with ReLU + softmax; get the shapes right on paper first",
      "Derive and implement backprop by hand; verify with numerical gradient checks",
      "Mini-batch SGD training loop; plot train/val loss and accuracy curves",
      "Tune learning rate and hidden size; document what moved the needle",
      "Confusion matrix — look at the actual images it gets wrong",
    ],
    stretchGoals: [
      "Add a second hidden layer and dropout (derive its backward pass)",
      "Reimplement in PyTorch in 30 minutes and marvel at the diff",
    ],
    skills: ["vectorized NumPy", "backprop derivation", "training loops", "learning-curve reading"],
    topicSlugs: ["neural-nets-backprop", "numpy-pandas", "linear-algebra", "training-dynamics"],
  },
  {
    slug: "sentiment-classifier",
    pillar: "ai",
    title: "Sentiment Classifier — Classical vs Neural",
    tagline: "TF-IDF + logistic regression vs a fine-tuned transformer, honestly evaluated.",
    difficulty: "easy",
    estHours: 8,
    overview:
      "Classify movie reviews (IMDB) three ways: TF-IDF + logistic regression, TF-IDF + gradient-boosted trees, and a fine-tuned DistilBERT. The point is the evaluation discipline: proper splits, cross-validation, precision/recall trade-offs, and an error analysis notebook comparing where each model fails. Spoiler: the classical baseline is embarrassingly strong — and learning that lesson early will save you from over-engineering forever.",
    buildSteps: [
      "Load IMDB, create leak-free train/val/test splits",
      "Baseline: TF-IDF + logistic regression with cross-validated hyperparameters",
      "Second baseline: gradient-boosted trees on the same features",
      "Fine-tune DistilBERT with Hugging Face Trainer on the same splits",
      "Compare all three: accuracy, F1, inference latency, and model size in one table",
      "Error analysis: 30 misclassified examples per model — categorize the failure patterns",
    ],
    stretchGoals: [
      "Calibration curves — are the predicted probabilities trustworthy?",
      "Serve the winner behind a FastAPI endpoint with request logging",
    ],
    skills: ["scikit-learn pipelines", "evaluation rigor", "HF fine-tuning basics", "error analysis"],
    topicSlugs: ["regression", "trees-ensembles", "model-evaluation", "data-prep-viz"],
  },
  {
    slug: "image-classifier",
    pillar: "ai",
    title: "Transfer-Learning Image Classifier",
    tagline: "Fine-tune a pretrained ResNet on your own photo categories, then deploy it.",
    difficulty: "easy",
    estHours: 8,
    overview:
      "Take a pretrained ResNet, freeze the backbone, and fine-tune it to classify a dataset you assemble yourself (pet breeds, food, your own photo library — anything with 3-10 classes). Transfer learning is the single most practical deep-learning pattern: 90% of applied CV work looks exactly like this. Finish by deploying it behind an endpoint with a drag-and-drop upload page.",
    buildSteps: [
      "Assemble a small dataset (500+ images, 3-10 classes); build train/val loaders with augmentation",
      "Fine-tune only the final layer of a pretrained ResNet18; establish the baseline",
      "Unfreeze deeper layers with a lower LR; compare against the frozen baseline",
      "Diagnose overfitting from the curves; add augmentation/regularization accordingly",
      "Grad-CAM visualizations — check the model looks at the right pixels",
      "Serve with FastAPI + a minimal upload UI",
    ],
    stretchGoals: [
      "Export to ONNX and measure CPU inference speedup",
      "Try a modern backbone (EfficientNet/ViT) and compare",
    ],
    skills: ["PyTorch", "transfer learning", "data augmentation", "model deployment"],
    topicSlugs: ["cnns", "training-dynamics", "serving-mlops"],
  },
  {
    slug: "train-nanogpt",
    pillar: "ai",
    title: "Train a nanoGPT",
    tagline: "Character-level GPT on Shakespeare — attention implemented by your own hands.",
    difficulty: "hard",
    estHours: 20,
    overview:
      "Follow Karpathy's 'Let's build GPT' to implement a decoder-only transformer from scratch — token/position embeddings, multi-head self-attention, causal masking, MLP blocks — and train it on tiny-Shakespeare until it generates plausible Elizabethan dialogue. Then push further: train on your own corpus. This is the project that makes the entire LLM era legible; every architecture diagram you see afterward is just this code at bigger scale.",
    buildSteps: [
      "Bigram baseline model + character tokenizer + sampling loop (get end-to-end generation working first)",
      "Single self-attention head with causal masking — the crux; understand every line",
      "Multi-head attention + feed-forward blocks + residuals + layer norm",
      "Scale to ~10M params, train on tiny-Shakespeare (GPU or MPS), sample results",
      "Ablate: remove residuals, then layer norm — watch training break; write down why",
      "Retrain on a corpus you care about (your notes, code, song lyrics-free text)",
    ],
    stretchGoals: [
      "Swap the char tokenizer for BPE you train yourself",
      "Implement KV-cache inference and measure the generation speedup",
      "Fine-tune your trained model on a tiny instruction dataset",
    ],
    skills: ["transformer architecture", "attention", "PyTorch training at scale", "ablation studies"],
    topicSlugs: ["attention-transformers", "llm-training", "tokenization", "training-dynamics"],
  },
  {
    slug: "lora-finetune",
    pillar: "ai",
    title: "LoRA Fine-tune a Small LLM",
    tagline: "Specialize a 1-3B open model on consumer hardware with parameter-efficient tuning.",
    difficulty: "medium",
    estHours: 12,
    overview:
      "Fine-tune a small open model (Llama-3.2-1B/3B or Qwen-2.5 class) with LoRA/QLoRA to do one thing well — mimic your writing style, answer questions about a niche domain, or follow a custom output format. Covers the full applied loop: dataset curation, PEFT training, before/after evaluation, and the honest question 'did fine-tuning actually beat few-shot prompting?' — which is exactly the judgment call AI engineers get paid for.",
    buildSteps: [
      "Pick a task and build a 200-1000 example instruction dataset (quality over quantity)",
      "Establish the baseline: how far does prompting alone get the base model?",
      "QLoRA fine-tune with HF PEFT (or MLX/Unsloth on Mac); log to a tracker",
      "Sweep LoRA rank and LR once each; note the effect",
      "Blind A/B eval: base+prompting vs fine-tuned on 50 held-out inputs",
      "Merge adapters and run the result locally (llama.cpp/Ollama)",
    ],
    stretchGoals: [
      "DPO pass on preference pairs after SFT",
      "Quantize to 4-bit GGUF and measure quality loss on your eval set",
    ],
    skills: ["PEFT/LoRA", "dataset curation", "eval design", "local inference"],
    topicSlugs: ["fine-tuning", "llm-training", "llm-evaluation"],
  },
  {
    slug: "rag-notes",
    pillar: "ai",
    title: "RAG Over Your Own Notes",
    tagline: "Chat with your notes: chunking, pgvector, hybrid search, citations — measured, not vibed.",
    difficulty: "medium",
    estHours: 15,
    overview:
      "Build retrieval-augmented generation over your personal knowledge base (Obsidian vault, bookmarks, docs): chunk and embed documents into pgvector, retrieve with hybrid (vector + keyword) search, rerank, and answer questions with inline citations back to sources. The differentiator is the retrieval eval set you build — 30 question/answer pairs that let you measure recall@k and actually know whether each change helped. That habit is what separates RAG engineers from RAG tourists.",
    buildSteps: [
      "Ingestion pipeline: parse markdown/PDFs, chunk with overlap, embed, store in pgvector",
      "Basic RAG loop: embed query → top-k retrieve → stuff context → answer with citations",
      "Build a 30-question eval set with known source chunks; measure recall@5 and answer quality",
      "Add hybrid search (BM25/tsvector + vector, reciprocal rank fusion); re-measure",
      "Add a reranker (cross-encoder or LLM-based); re-measure",
      "Streamlit or simple web UI with source-chunk display",
    ],
    stretchGoals: [
      "Query rewriting/decomposition for multi-hop questions",
      "Incremental sync — re-embed only changed files",
      "Compare chunk sizes (256/512/1024) on your eval set",
    ],
    skills: ["embeddings", "vector search", "retrieval evaluation", "LLM app plumbing"],
    topicSlugs: ["rag-vector-dbs", "embeddings", "llm-evaluation", "prompt-engineering"],
  },
  {
    slug: "semantic-search",
    pillar: "ai",
    title: "Semantic Search Engine",
    tagline: "Meaning-based search over 10K+ documents, with ANN indexing you understand.",
    difficulty: "medium",
    estHours: 10,
    overview:
      "Build search that finds 'ways to speed up a slow database' when the document says 'query optimization techniques': embed a 10K+ document corpus (e.g., Hacker News titles, arXiv abstracts), serve nearest-neighbor queries, and compare exact brute-force search against an HNSW index for the speed/recall trade-off. A tight, self-contained project that makes embedding geometry and ANN indexing concrete before you rely on them inside bigger RAG systems.",
    buildSteps: [
      "Pull a corpus (HN titles via BigQuery/API, or arXiv abstracts); embed with a sentence-transformer",
      "Brute-force cosine search with NumPy — correct first, fast later",
      "Add HNSW (hnswlib or pgvector index); measure recall@10 vs brute force and the latency win",
      "Search API + minimal UI with query-time embedding",
      "Side-by-side demo page: keyword search vs semantic search on the same queries",
    ],
    stretchGoals: [
      "2-D UMAP visualization of the embedding space, colored by topic",
      "Multilingual queries against an English corpus (multilingual embedding model)",
    ],
    skills: ["sentence embeddings", "ANN indexes", "recall/latency trade-offs", "search UX"],
    topicSlugs: ["embeddings", "rag-vector-dbs", "svm-knn-clustering"],
  },
  {
    slug: "tool-using-agent",
    pillar: "ai",
    title: "Tool-Using Agent from Scratch",
    tagline: "The agent loop with no framework: tools, multi-step reasoning, guardrails.",
    difficulty: "medium",
    estHours: 15,
    overview:
      "Build an agent directly on a model API (Claude or an open model) with zero agent frameworks: define tools (calculator, web fetch, file read/write, your Cortex API), implement the reason→act→observe loop, and give it tasks requiring multi-step tool chains. Writing the loop yourself — including the failure handling, retries, and guardrails — teaches you exactly what LangChain-style abstractions hide, and agentic engineering is the most in-demand AI skill right now.",
    buildSteps: [
      "Single-tool loop: model + calculator via native tool-calling; handle the tool-result round-trip",
      "Tool registry with JSON-schema definitions; add web-fetch and file tools",
      "Multi-step tasks: 'fetch this page, extract X, compute Y, save to file' — loop until done with a step budget",
      "Failure handling: malformed tool calls, tool errors fed back to the model, retry limits",
      "Guardrails: confirmation gate before write/destructive tools; log every step structured",
      "Eval: 10 fixed tasks, measure task completion rate across prompt iterations",
    ],
    stretchGoals: [
      "Expose your tools as an MCP server and connect a real client",
      "Two-agent pattern: planner delegates to executor",
      "Cost/latency tracking per task",
    ],
    skills: ["tool calling", "agent loops", "guardrail design", "structured logging", "evals"],
    topicSlugs: ["agents-tool-use", "prompt-engineering", "llm-evaluation"],
  },
  {
    slug: "eval-harness",
    pillar: "ai",
    title: "LLM Eval Harness",
    tagline: "A regression-test suite for prompts: golden sets, LLM-as-judge, diff reports.",
    difficulty: "medium",
    estHours: 10,
    overview:
      "Build the missing test suite for LLM apps: define eval cases in YAML (input, expected properties), run them against multiple prompts/models, grade with exact-match, regex, and LLM-as-judge graders, and produce a diff report showing exactly which cases regressed when you changed a prompt. Point it at your own RAG/agent projects. Teams live or die by this loop — building your own harness once makes you the person who sets it up everywhere you work.",
    buildSteps: [
      "YAML case format: input, ideal output/properties, grader type; runner that executes N cases against a prompt+model config",
      "Graders: exact match, regex/contains, and numeric tolerance",
      "LLM-as-judge grader with a rubric prompt; validate it against 20 hand-labeled cases first",
      "Side-by-side run comparison: prompt A vs prompt B, per-case diff table (improved/regressed/unchanged)",
      "Caching + parallel execution so re-runs are fast and cheap",
      "Wire it to one of your real projects (RAG or agent) and do one genuine prompt-improvement cycle",
    ],
    stretchGoals: [
      "HTML report with per-case drill-down",
      "CI integration: fail the build if pass-rate drops below a threshold",
    ],
    skills: ["eval design", "LLM-as-judge", "test infrastructure", "prompt iteration discipline"],
    topicSlugs: ["llm-evaluation", "prompt-engineering", "model-evaluation"],
  },
];
