import type { ProjectSpec } from "../types";

export const systemDesignProjects: ProjectSpec[] = [
  {
    slug: "url-shortener",
    pillar: "system_design",
    title: "URL Shortener — the Full Treatment",
    tagline: "Not the toy version: ID generation, cache layer, shard-ready storage, analytics.",
    difficulty: "medium",
    estHours: 20,
    overview:
      "Build bit.ly for real: short-code generation with base62 counters vs random codes (implement both, discuss collisions), a Redis cache in front of Postgres, 302 redirects with sub-10ms p99 on cache hits, and an async click-analytics pipeline. This is THE canonical system design question — having actually built it, measured it, and hit its bottlenecks puts your interview answer in a different league from people who've only read about it.",
    buildSteps: [
      "FastAPI service: POST /shorten and GET /{code} with Postgres storage",
      "Implement both ID strategies (base62 auto-increment + random-with-retry); write up the trade-off",
      "Add Redis cache-aside on the redirect path; measure p50/p99 before and after with a load tool (hey/wrk)",
      "Async click tracking: push events to a queue, aggregate counts in a worker (never block the redirect)",
      "Hash-partition the links table by code prefix to demonstrate a shard-ready layout",
      "Add rate limiting on the shorten endpoint (reuse your rate-limiter library)",
    ],
    stretchGoals: [
      "Custom vanity codes with reserved-word handling",
      "Link expiry + a cleanup job; cache invalidation on delete",
      "A tiny dashboard page showing per-link click charts",
    ],
    skills: ["caching", "load testing", "async pipelines", "partitioning", "API design"],
    topicSlugs: ["design-url-shortener", "caching", "sharding", "rate-limiting"],
  },
  {
    slug: "raft-kv-store",
    pillar: "system_design",
    title: "Distributed KV Store with Raft",
    tagline: "Three nodes, leader election, log replication — consensus you built yourself.",
    difficulty: "hard",
    estHours: 40,
    overview:
      "Implement the Raft consensus algorithm and use it to power a replicated key-value store: three processes that elect a leader, replicate a command log, apply entries to a state machine, and survive you killing any node mid-write. This is the deepest systems project on the list — the one that transforms 'consensus' from a word you say in interviews into something you have debugged at 2am. Modeled on MIT 6.824's famous lab series.",
    buildSteps: [
      "Leader election: terms, randomized election timeouts, RequestVote RPCs between 3 local processes",
      "Log replication: AppendEntries, commit index advancement, follower catch-up",
      "KV state machine on top: GET/PUT/DELETE applied from committed log entries",
      "Persistence: write term/votedFor/log to disk; recover correctly after restart",
      "Chaos test: script that kills/restarts random nodes during writes and asserts no acknowledged write is ever lost",
      "Client with leader discovery and retry-on-redirect",
    ],
    stretchGoals: [
      "Log compaction with snapshots",
      "Linearizable reads via ReadIndex instead of going through the log",
      "Membership changes (add a 4th node live)",
    ],
    skills: ["consensus", "RPC design", "failure testing", "state machines", "persistence"],
    topicSlugs: ["consensus", "replication", "clocks-ordering", "idempotency-retries"],
  },
  {
    slug: "realtime-chat",
    pillar: "system_design",
    title: "Realtime Chat System",
    tagline: "WebSockets, presence, delivery states, and fan-out — Discord in miniature.",
    difficulty: "medium",
    estHours: 25,
    overview:
      "A multi-room chat app with WebSocket connections, online presence, typing indicators, message persistence, unread counts, and delivery/read receipts. The interesting part isn't the UI — it's connection state management, ordering guarantees, and what happens when a user has three tabs open or reconnects after a subway tunnel. Directly exercises the 'design a chat system' interview question end to end.",
    buildSteps: [
      "WebSocket gateway (FastAPI websockets or Node ws): rooms, join/leave, broadcast",
      "Message persistence with monotonic per-room sequence numbers; history pagination API",
      "Reconnect protocol: client sends last-seen sequence, server replays the gap",
      "Presence + typing indicators with heartbeat timeouts",
      "Delivery states (sent/delivered/read) and unread counts per room",
      "Multi-instance mode: run two gateway processes with Redis pub/sub fan-out between them",
    ],
    stretchGoals: [
      "Push-notification hook for offline users",
      "Message search with Postgres full-text search",
      "Load test: 1K simulated concurrent connections, measure fan-out latency",
    ],
    skills: ["WebSockets", "pub/sub", "ordering & reconnection", "stateful service scaling"],
    topicSlugs: ["design-chat", "api-styles", "message-queues"],
  },
  {
    slug: "rate-limiter-service",
    pillar: "system_design",
    title: "Distributed Rate Limiter Service",
    tagline: "A standalone limiter with Redis backing that other services call — like Stripe's.",
    difficulty: "medium",
    estHours: 15,
    overview:
      "Promote your rate-limiter library into a network service: a sidecar/API that any app can ask 'is this request allowed?', backed by Redis with atomic Lua scripts so multiple app instances share one budget. Covers the real production concerns: atomicity under concurrency, fail-open vs fail-closed when Redis dies, latency budgets, and returning proper 429s with Retry-After. A compact project that touches an unreasonable number of interview topics.",
    buildSteps: [
      "Service with POST /check {key, cost} → allow/deny + remaining/reset metadata",
      "Redis-backed sliding window counter as an atomic Lua script (no read-modify-write races)",
      "Concurrency test: hammer one key from 50 parallel clients, assert the budget is never exceeded",
      "Fail-open/fail-closed config with circuit breaker when Redis is unreachable",
      "FastAPI middleware client that consults the limiter and sets X-RateLimit-* headers",
      "Grafana-style metrics: allow/deny rates, decision latency histogram",
    ],
    stretchGoals: [
      "Token bucket variant with per-key config (different tiers)",
      "Local in-process cache layer that pre-allocates small budgets to cut Redis round-trips",
    ],
    skills: ["Redis + Lua atomicity", "concurrency testing", "failure-mode design", "middleware"],
    topicSlugs: ["rate-limiting", "caching", "idempotency-retries"],
  },
  {
    slug: "mini-message-queue",
    pillar: "system_design",
    title: "Message Queue from Scratch",
    tagline: "Append-only log, consumer groups, acks, and redelivery — a pocket Kafka.",
    difficulty: "hard",
    estHours: 30,
    overview:
      "Build a durable message broker: producers append to a partitioned commit log on disk, consumers track offsets, consumer groups share partitions, and unacked messages get redelivered after a visibility timeout. Building the thing teaches you why Kafka made every design choice it made — segment files, offsets-not-deletes, consumer-side state — knowledge that transfers straight into any event-driven design discussion.",
    buildSteps: [
      "Append-only log: segment files with length-prefixed records; index file for offset → position",
      "Producer/consumer API over HTTP or gRPC: publish, fetch-from-offset, commit-offset",
      "Consumer groups: partition assignment and rebalancing when consumers join/leave",
      "At-least-once delivery: visibility timeout + redelivery of unacked messages; dead-letter after N attempts",
      "Crash test: kill the broker mid-write, verify no committed message is lost on restart (fsync policy)",
      "Throughput benchmark: single vs batched publishes; document the numbers",
    ],
    stretchGoals: [
      "Log compaction by key",
      "Replication to a follower broker with leader failover",
    ],
    skills: ["file I/O & durability", "offset management", "protocol design", "crash testing"],
    topicSlugs: ["message-queues", "event-driven-streams", "replication"],
  },
  {
    slug: "news-feed-service",
    pillar: "system_design",
    title: "News Feed Service",
    tagline: "Fan-out on write vs read, implemented both ways and benchmarked.",
    difficulty: "medium",
    estHours: 20,
    overview:
      "Build a follow-graph + posts + timeline service and implement BOTH feed strategies: fan-out-on-write (push to follower timelines at post time) and fan-out-on-read (aggregate at request time), then benchmark them against a simulated celebrity with 100K followers. The push/pull trade-off is the heart of the news-feed interview question; having graphs of your own measurements is an unfair advantage.",
    buildSteps: [
      "Core models: users, follows, posts; seed a synthetic social graph with a power-law follower distribution",
      "Fan-out-on-read: timeline = merge recent posts from followees at request time (K-way merge by time)",
      "Fan-out-on-write: on post, push IDs into each follower's Redis timeline list",
      "Benchmark both under load: post latency vs read latency, especially for the 100K-follower account",
      "Hybrid: push for normal users, pull for celebrities — the real-world answer",
      "Cursor-based pagination that stays stable while new posts arrive",
    ],
    stretchGoals: [
      "Simple ranking (recency + engagement score) instead of pure chronological",
      "Feed cache invalidation on unfollow/delete",
    ],
    skills: ["fan-out strategies", "Redis lists", "K-way merge", "benchmarking", "pagination"],
    topicSlugs: ["design-news-feed", "caching", "heaps"],
  },
  {
    slug: "web-crawler",
    pillar: "system_design",
    title: "Polite Distributed Web Crawler",
    tagline: "Frontier queue, per-domain politeness, bloom-filter dedup, multiple workers.",
    difficulty: "medium",
    estHours: 18,
    overview:
      "A crawler that starts from seed URLs and fetches a bounded corpus while being a good citizen: robots.txt compliance, per-domain rate limits, URL dedup with a bloom filter, and multiple worker processes sharing a frontier queue. Crawlers are a favorite interview design because they force queues + dedup + rate limiting + failure handling into one system — this project is all four, running on your laptop.",
    buildSteps: [
      "Single-threaded crawler: fetch → parse links → normalize URLs → enqueue; hard page-count budget",
      "robots.txt parsing and per-domain politeness delay (token bucket per host)",
      "Dedup: exact-set first, then a bloom filter; measure memory at 1M URLs and false-positive rate",
      "Frontier as a Redis queue; run 4 worker processes sharing it without double-fetching",
      "Failure handling: timeouts, retry with backoff, permanent-failure list; structured crawl log",
      "Store page text + metadata; simple keyword search CLI over the corpus",
    ],
    stretchGoals: [
      "Priority frontier (PageRank-ish score or domain diversity)",
      "Content-hash dedup for mirror pages",
      "Sitemap.xml ingestion",
    ],
    skills: ["queues", "bloom filters", "politeness/rate limiting", "worker coordination"],
    topicSlugs: ["design-web-crawler", "message-queues", "rate-limiting", "hashing"],
  },
];
